import { useEffect, useState } from "react";
import { BarChart3, PauseCircle, PlayCircle, ShieldCheck } from "lucide-react";
import { DEFAULT_SETTINGS } from "../shared/constants";
import { sendMessage } from "../shared/messages";
import type { FeedRuntimeStatus, Settings } from "../shared/types";
import { BrandMark, BrandName } from "../shared/Brand";
const extensionRuntimeAvailable = typeof chrome !== "undefined" && Boolean(chrome.runtime?.id);
const extensionVersion = extensionRuntimeAvailable ? chrome.runtime.getManifest().version : "geliştirme";
export function Popup(){const [settings,setSettings]=useState<Settings>(DEFAULT_SETTINGS);const [feed,setFeed]=useState<FeedRuntimeStatus>();const [error,setError]=useState("");useEffect(()=>{if(!extensionRuntimeAvailable)return;Promise.all([sendMessage<Settings>({type:"GET_SETTINGS"}).then(setSettings),sendMessage<FeedRuntimeStatus|undefined>({type:"GET_FEED_STATE"}).then(setFeed)]).catch(()=>setError("Eklenti yenilendi. Bu pencereyi kapatıp tekrar aç."))},[]);const toggle=async()=>{try{const next={...settings,trackingEnabled:!settings.trackingEnabled};if(extensionRuntimeAvailable)await sendMessage({type:"SET_SETTINGS",settings:next});setSettings(next);setError("")}catch{setError("Takip ayarı kaydedilemedi. Eklentiyi yenileyip tekrar dene.")}};return <main className="popup"><header><span><BrandMark size={34}/></span><div><strong><BrandName/></strong><small>Yerel-first izleme analizi · v{extensionVersion}</small></div><b className={`popup-status ${settings.trackingEnabled?"active":""}`}>{settings.trackingEnabled?"Aktif":"Kapalı"}</b></header>{error?<p className="popup-error" role="alert">{error}</p>:null}<section><div className={`status-dot ${settings.trackingEnabled?"active":""}`}/><div><strong>{settings.trackingEnabled?"Takip açık":"Takip duraklatıldı"}</strong><p>{settings.trackingEnabled?"YouTube oturumları yerel olarak kaydediliyor.":"Yeni oturum kaydedilmiyor."}</p></div></section><section><div className={`status-dot ${feed?.state==="active"?"active":""}`}/><div><strong>Keşfet analizi</strong><p>{feed?.message??"YouTube ana sayfası bekleniyor."}</p></div></section><button className="button" onClick={()=>void toggle()}>{settings.trackingEnabled?<PauseCircle size={17}/>:<PlayCircle size={17}/>} {settings.trackingEnabled?"Takibi durdur":"Takibi başlat"}</button><button className="button primary" onClick={()=>{if(extensionRuntimeAvailable)void chrome.runtime.openOptionsPage()}}><BarChart3 size={17}/>Dashboard'u aç</button><footer><ShieldCheck size={15}/>Bulut yalnızca sen etkinleştirirsen kullanılır.</footer></main>}
